#!/usr/bin/env bash
# Install nginx and start it
apt-get -y update;
apt-get -y install nginx;
ufw allow 'Nginx HTTP';
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html;
service nginx restart;
